export const actions = {
  UPDATE_BOARDS: 'UPDATE_BOARDS',
  UPDATE_BOARDS_SUCCESS: 'UPDATE_BOARDS_SUCCESS',
  FETCH_ALL_BOARDS: 'FETCH_ALL_BOARDS',
  FETCH_ALL_BOARDS_SUCCESS: 'FETCH_ALL_BOARDS_SUCCESS',
};
