export const actionLabels = {
  ASYNC_UPDATE_BOARDS: 'ASYNC_UPDATE_BOARDS',
  UPDATE_BOARDS_SUCCESS: 'UPDATE_BOARDS_SUCCESS',
  ASYNC_FETCH_ALL_BOARDS: 'ASYNC_FETCH_ALL_BOARDS',
  FETCH_ALL_BOARDS_SUCCESS: 'FETCH_ALL_BOARDS_SUCCESS',
  SET_BOARD_VIEW: 'SET_BOARD_VIEW',
};
